### ISSUE TITLE
Place to talk about node-xmpp

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp.github.io#7]
Is there any public MUC room/forum to talk about node-xmpp?
It could be added to the website homepage.

**Comment by lloydwatkin** [comment]
There isn't currently. We'd need a web interface for people learning XMPP. I'd be tempted to use Gitter but that seems very wrong. I'll ask @imaginator if he's kindly allow us to have a MUC on the buddycloud server.

**Comment by sonnyp** [comment]
@lloydwatkin actually I think a large portion of node-xmpp-* users do not even have an XMPP account so I'll be okay with gitter.

https://github.com/gitterHQ/gitter/issues/248

**Comment by chris-rock** [comment]
we could use duckduckgo?

**Comment by sonnyp** [comment]
also I think xmpp.org has MUC.

**Comment by imaginator** [comment]
Funny I was just thinking of moving buddycloud.org over to the hosting platform (which doesn't run MUC) and migrating to buddycloud@conference.jabber.org. Otherwise I'd have been more than happy.

**Comment by imaginator** [comment]
I've heard issues about DDG's xmpp recently.

**Comment by lloydwatkin** [comment]
@chris-rock are you at the summit/FOSDEM? We should organise a chat about this.

**Comment by chris-rock** [comment]
@lloydwatkin Would be cool, but unfortunately not.

**Comment by sonnyp** [comment]
I've created the room node-xmpp@conference.dukgo.com

**Comment by lloydwatkin** [comment]
:+1:

**Comment by sonnyp** [comment]
Guys, I have registered node-xmpp.org
http://node-xmpp.org/ I have deployed the website there and added a prosody virtual host on my server.

The new MUC is node-xmpp@muc.node-xmpp.org.

I'm also adding candy chat / anonymous login so there will be a webchat for people with no XMPP account/client.

**Comment by chris-rock** [comment]
@sonnyp very cool. You could use startssl, which offer free certs for one domain: http://www.startssl.com/
